<span id="top"></span>

<header id="masthead">
	<div class="container">
	
		<!-- C.1.1. Logo -->
        
        <a href="#top" rel="home" class="astd-textLink nav-front">
        	<img src="<?php print base_path() . path_to_theme() .'/' ?>assets/images/site/logo.png" alt="Textshelf Logo" class="logo" id="logo-textshelf" />
		</a>
		<!-- C.1.1. Navigation -->
		
		<a class="reveal mobile-nav" href="#nav-mobile"><img src="<?php print base_path() . path_to_theme() .'/' ?>assets/images/svg/icon-burger.svg" /></a>
        
        <p>hello world</p>
		
        <nav id="nav" class="nav">

			<ul>

				<li><a href="#section-events" class="first astd-textLink">Events</a></li>
				<li><a href="#section-conferences" class="astd-textLink">Conference</a></li>
				<li><a href="#section-about" class="astd-textLink">About ASTD</a></li>
				<li><a href="#footend" class="astd-textLink">Contact Us</a></li>
				<li><a href="#section-members" class="astd-textLink">Become a Member</a></li>
				<li><a href="http://test.astd.co.za/user" class="astd-textLink">Login</a></li>

			</ul>

		</nav>
		
		<nav id="nav-mobile" class="not-active">

			<ul>

				<li><a href="http://test.astd.co.za/calendar">Events</a></li>
				<li><a href="#section-conferences">Conferences</a></li>
				<li><a href="http://test.astd.co.za/about">About ASTD</a></li>
				<li><a href="#footend" class="astd-textLink">Contact Us</a></li>
				<li><a href="http://test.astd.co.za/member">Become a Member</a></li>
				<li><a href="http://test.astd.co.za/user">Login</a></li>

			</ul>

		</nav>

	</div>
</header>